### ISSUE TITLE
Technisch spul/beslissingen

### ISSUE THREAD

**Issue by WouterBrookhuis** [bramkelder/MonoGear#2]
- Entity collection/manager
- Lighting/zicht
- Level setup
- Y omhoog of omlaag? (y = 0 boven of onder aan het scherm?)
- Schaal (1 unit = 1 pixel? of pixels en schaal loskoppelen? mogelijk makkelijker voor resolutie aanpassen met UWP)
- Resource management (bijv. sprite collection voor laden ipv per entity/class?)
- Pathfinding (obviously)

**Comment by b-kelder** [comment]
- How to levels?
